# This is a basic workflow to help you get started with Actions

name: Publsh to docker hub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags: 
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and push Backend
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{secrets.DOCKER_USER}}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{secrets.DOCKER_PASS}}
          # Docker repository to tag the image with
          repository: relucri/wotfarm-backend
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Path to the build context
          path: ./backend
      - name: Build and push Frontend
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{secrets.DOCKER_USER}}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{secrets.DOCKER_PASS}}
          # Docker repository to tag the image with
          repository: relucri/wotfarm
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: true
          # Path to the build context
          path: ./frontend
